# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Fetch Sources
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.3.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtmultimedia'
        aqtversion: '==2.0.5'

    - name: CMake Configure
      run:  |
        mkdir build
        cd %GITHUB_WORKSPACE%\build
        choco install ninja -y
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DQT_QMAKE_EXECUTABLE=qmake -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ../
      shell: cmd

    - name: Build Application
      run:  |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd %GITHUB_WORKSPACE%\build
        set CL=/MP
        cmake --build .
        cd bin
        dir
      shell: cmd

    - name: Package Application
      run: |
        cd %GITHUB_WORKSPACE%\build\bin
        windeployqt --qmldir %GITHUB_WORKSPACE% DeepInColorfulSpace.exe
        dir
        choco install 7zip -y
        cd %GITHUB_WORKSPACE%\build
        7z.exe a game.zip bin
      shell: cmd

    - name: Upload Application Package 
      uses: actions/upload-artifact@v1
      with:
        name: TheGame
        path: build/game.zip
